name: Build, Test and Push Docker Images
on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and test Task Service
      run: mvn -B package --file task-service/pom.xml -DskipTests

    - name: Build and test User Service
      run: mvn -B package --file user-service/pom.xml -DskipTests

  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Debug Docker Hub Username
        run: echo "Username from secrets is >>${{ secrets.DOCKERHUB_USERNAME }}<<"

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Task Service Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./task-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-api:latest

      - name: Build and push User Service Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-api:latest

#  deploy-to-minikube:
#    runs-on: self-hosted
#    needs: push-to-dockerhub
#    steps:
#      - uses: actions/checkout@v4
#      - name: Deploy to Minikube
#        run: |
#          kubectl apply -f k8s/
#          kubectl rollout restart deployment/nurassul-task-api-deployment
#          kubectl rollout restart deployment/nurassul-user-api-deployment


